_prefs: 
  saveCenter: true
_properties: {}
attribution: Map data © OpenStreetMap contributors
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -79.024658203125
  - 42.61779143282346
  - 6
description: ''
format: "png8:m=h:c=64"
interactivity_layer: ''
layers: null
maxzoom: 22
minzoom: 0
mtime: 1384802563610
name: Pinterest
scale: 1
source: "mapbox:///mapbox.mapbox-terrain-v1,mapbox.mapbox-streets-v4"
styles: 
  - style.mss
  - labels.mss
  - roads.mss
  - roadlabels.mss
template: ''
