_prefs: 
  saveCenter: true
_properties: {}
attribution: Map data © OpenStreetMap contributors
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -92.493896484375
  - 59.4115481664237
  - 6
description: Port of Toner to TileMill2, building on Aaron Lidman's Toner-for-TileMill work
format: "png8:m=h"
interactivity_layer: ''
maxzoom: 22
minzoom: 0
mtime: 1383868616167
name: color palette 5
scale: 1
source: "mapbox:///mapbox.mapbox-streets-v3"
styles: 
  - land.mss
  - roads.mss
  - boundaries.mss
  - palette.mss
  - labels.mss
template: ''
