_prefs: 
  saveCenter: true
_properties: {}
attribution: Map data © OpenStreetMap contributors
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -0.1925182342529297
  - 51.48090181941534
  - 16
description: ''
format: "png8:m=h"
interactivity_layer: ''
maxzoom: 22
minzoom: 0
mtime: 1384303072240
name: Pinterest 7
scale: 1
source: "mapbox:///mapbox.mapbox-streets-v4"
styles: 
  - style.mss
  - labels.mss
  - roads.mss
  - roadlabels.mss
template: ''
