_prefs: 
  saveCenter: true
_properties: {}
attribution: Map data © OpenStreetMap contributors
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -122.42666244506835
  - 37.80612209172951
  - 13
description: ''
format: png
interactivity_layer: ''
maxzoom: 22
minzoom: 0
mtime: 1383953888367
name: Pinterest 2
scale: 1
source: "mapbox:///mapbox.mapbox-streets-v4"
styles: 
  - style.mss
  - labels.mss
  - roadlabels.mss
template: ''
